### ISSUE TITLE
[Help] support unit test with vitest?

### ISSUE THREAD

**Issue by watonyweng** [electron-vite/electron-vite-vue#157]
#### Describe the problem you Confuse

Do we plan to support vitest?

#### More detail (optional)

If supported, I can contribute to the project

**Comment by caoxiemeihao** [comment]
@watonyweng Hey here! 👋
Thanks for you suggest.  
I think this template is not necessary to provide the test, because it is just a tempate.  
Just like the official [vue-ts](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vue-ts) template of Vite.

In fact,  [vite-plugin-electorn](https://github.com/electron-vite/vite-plugin-electron) needes test more.

**Comment by watonyweng** [comment]
@caoxiemeihao Thanks for your reply, we can add [options](https://github.com/electron-vite/create-electron-vite/blob/main/index.js#L10) for [vite-plugin-electron](https://github.com/electron-vite/vite-plugin-electron) to support vitest and playwright.
