### ISSUE TITLE
[Bug] preload exposure is not secure

### ISSUE THREAD

**Issue by Tanimodori** [electron-vite/electron-vite-vue#199]
#### Describe the bug

Currently this project load preload context by violating electron context isolation:

https://github.com/electron-vite/electron-vite-vue/blob/0406b1bf674e57fe9bb1e6d5eff314ed83ec82ab/electron/main/index.ts#L38-L39

Even get the secure warning disabled:

https://github.com/electron-vite/electron-vite-vue/blob/0406b1bf674e57fe9bb1e6d5eff314ed83ec82ab/electron/main/index.ts#L16

We should use `contextBridge.exposeInMainWorld` for secure exposure of preload context, manually or by a plugin like [unplugin-auto-expose](https://github.com/cawa-93/unplugin-auto-expose). If you do not want to include the example in this template, at least leave the secure warning alone to warn users that it is not secure to do that.

**Comment by caoxiemeihao** [comment]
## 🚨 Be aware

By default, this template integrates Node.js in the Renderer process. If you don't need it, you just remove the option below. [Because it will modify the default config of Vite](https://github.com/electron-vite/vite-plugin-electron/tree/main/packages/electron-renderer#config-presets-opinionated).

```diff
# vite.config.ts

electron({
- renderer: {}
})
```

**Comment by caoxiemeihao** [comment]
PR: https://github.com/electron-vite/electron-vite-vue/pull/214
